let data = {
    articalData:[
        {
            id:0,
            articalTitle:"让 BAT 的 Offer 不再难拿",
            author:"bestswifter",
            state:"审核通过",
            browser_right:"开放浏览",
            isshow:true,
            time:"2017-10-01",
            checked:false,
            isstore:false,
            right:true
        },
        {
            id:1,
            articalTitle:"最全前端开发面试问题及答案整理",
            author:"github.com",
            state:"待审核",
            browser_right:"开放浏览",
            isshow:false,
            time:"2016-03-12",
            checked:false,
            isstore:false,
            right:false
        },
        {
            id:2,
            articalTitle:"secction",
            author:"bestswifter",
            state:"审核通过",
            browser_right:"开放浏览",
            isshow:true,
            time:"2017-10-01",
            checked:false,
            isstore:false,
            right:true
        }
    ],
    memberData:[
        {
            id:1,
            userName:"Yolanda",
            type:"普通用户",
            state:'normal',
            loadingTimes:105,
            latelyLoadingIP:'107.120.117',
            registerTime:'2017-11-10',
            enable:true,
            password:'zyy1221',
            checked:false,
        },
        {
            id:2,
            userName:"Eric",
            type:"管理员",
            state:'management',
            loadingTimes:105,
            latelyLoadingIP:'107.120.117',
            registerTime:'2017-11-10',
            enable:false,
            password:'zyy1221',
            checked:false,
        },
        {
            id:3,
            userName:"木棉",
            type:"普通用户",
            state:'normal',
            loadingTimes:105,
            latelyLoadingIP:'107.120.117',
            registerTime:'2017-11-10',
            enable:true,
            password:'zyy1221',
            checked:false,
        },
        {
            id:4,
            userName:"风清扬",
            type:"普通用户",
            state:'normal',
            loadingTimes:105,
            latelyLoadingIP:'107.120.117',
            registerTime:'2018-01-01',
            enable:true,
            password:'zyy1221',
            checked:false,
        }
    ],
    system:[
            {
                id:1,
                name:'系统首页',
                iconUrl:'fa fa-television',
                address:"/manage"
            },
            {
                id:2,
                name:'商品管理',
                iconUrl:'fa fa-files-o',
                address:"/artical"
            },
            {
                id:3,
                name:'会员管理',
                iconUrl:'fa fa-users',
                address:"/member#all"
            },
            {
                id:4,
                name:'登陆界面',
                iconUrl:'fa fa-user-circle-o',
                address:"/login"
            }
        ]
    }

export default data;